Feat/consume cms endpoints web
alpha-global/bioy-marketing pull request #86
Opened 2023-10-16 12:56 UTC by timosville

Card: https://trello.com/c/fol3ffGJ/1552-consume-cms-endpoints-web

2023-10-16 15:01 UTC, JannieT requested changes
Cool! 
Please take a look at all the possible markdown fields, not only the ones inside the wisdom/NT/OT sections.

2023-10-16 15:01 UTC, JannieT commented on utils/shortcodes.js
> +  let rendered = marked
I just had to tweak this function to prevent a crash on the server:

```suggestion
  if (!markdown) return '';
 
  let rendered = marked
```

2023-10-17 06:28 UTC, JannieT requested changes
Almost there. Please check the [bundle definition](https://github.com/alpha-global/bioy-cms/blob/ed7a74385996f1d07efdfea357367508f316143b/config/story.ts#L14) to make sure we catch all the markdown fields. I have shown two examples of the further changes needed in the PR comments.

2023-10-17 06:28 UTC, JannieT commented on src/devotions/devotions.njk
> +      {{ devotion.bundle.verseOfTheDay.verse|safe }}
```suggestion
      {{ devotion.bundle.verseOfTheDay.verse|markdown|safe }}
```

2023-10-17 06:28 UTC, JannieT commented on src/devotions/devotions.njk
> +    {{ devotion.bundle.pippa|safe }}
```suggestion
    {{ devotion.bundle.pippa|markdown|safe }}
```

2023-10-17 10:25 UTC, timosville commented on src/devotions/devotions.njk
> +      {{ devotion.bundle.verseOfTheDay.verse|safe }}
I missed that. Thank you.

2023-10-17 10:57 UTC, JannieT approved these changes

2023-10-17 10:57 UTC, merged